name: Makefile CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: sudo apt install mono-devel
      
    - name: Build everything
      run: make
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        path: class/lib/net_4_5
        if-no-files-found: error
        retention-days: 2
    
      
